# Generated by Django 6.0.7 on 2026-07-08 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('output_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('json', 'JSON')], default='csv', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('runtime', models.FloatField(help_text='Execution time in seconds')),
                ('output_format', models.CharField(max_length=10)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Summary of operations performed')),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='pipelines.pipeline')),
            ],
            options={
                'verbose_name_plural': 'processing histories',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('operation', models.CharField(choices=[('remove_duplicates', 'Remove Duplicates'), ('fill_missing', 'Fill Missing Values'), ('trim_spaces', 'Trim Spaces'), ('normalize_text', 'Normalize Text'), ('standardize_capitalization', 'Standardize Capitalization'), ('rename_columns', 'Rename Columns'), ('convert_dtype', 'Convert Data Type'), ('format_dates', 'Format Dates'), ('uppercase', 'Uppercase'), ('lowercase', 'Lowercase'), ('title_case', 'Title Case'), ('remove_special_chars', 'Remove Special Characters'), ('add_derived_column', 'Add Derived Column'), ('validate_emails', 'Validate Emails'), ('validate_phones', 'Validate Phones'), ('validate_dates', 'Validate Dates'), ('detect_outliers_iqr', 'Detect Outliers (IQR)'), ('detect_outliers_zscore', 'Detect Outliers (Z-Score)'), ('merge_datasets', 'Merge Datasets'), ('convert_format', 'Convert Format')], max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pipelines.pipeline')),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('pipeline', 'step_order')},
            },
        ),
    ]
