# Generated by Django 6.0.7 on 2026-07-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_processinghistory_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinestep',
            name='operation',
            field=models.CharField(choices=[('remove_duplicates', 'Remove Duplicates'), ('fill_missing', 'Fill Missing Values'), ('trim_spaces', 'Trim Spaces'), ('normalize_text', 'Normalize Text'), ('standardize_capitalization', 'Standardize Capitalization'), ('rename_columns', 'Rename Columns'), ('convert_dtype', 'Convert Data Type'), ('format_dates', 'Format Dates'), ('uppercase', 'Uppercase'), ('lowercase', 'Lowercase'), ('title_case', 'Title Case'), ('remove_special_chars', 'Remove Special Characters'), ('regex_replace', 'Regex Find & Replace'), ('add_derived_column', 'Add Derived Column'), ('validate_emails', 'Validate Emails'), ('validate_phones', 'Validate Phones'), ('validate_dates', 'Validate Dates'), ('detect_outliers_iqr', 'Detect Outliers (IQR)'), ('detect_outliers_zscore', 'Detect Outliers (Z-Score)'), ('merge_datasets', 'Merge Datasets')], max_length=50),
        ),
    ]
