# Generated by Django 6.0.7 on 2026-07-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_alter_pipelinestep_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinestep',
            name='operation',
            field=models.CharField(choices=[('remove_duplicates', 'Remove Duplicates'), ('fill_missing', 'Fill Missing Values'), ('trim_spaces', 'Trim Spaces'), ('normalize_text', 'Normalize Text'), ('standardize_capitalization', 'Standardize Capitalization'), ('rename_columns', 'Rename Columns'), ('convert_dtype', 'Convert Data Type'), ('auto_detect_dtypes', 'Auto Detect Data Types'), ('boolean_conversion', 'Boolean Conversion'), ('format_dates', 'Format Dates'), ('uppercase', 'Uppercase'), ('lowercase', 'Lowercase'), ('title_case', 'Title Case'), ('remove_special_chars', 'Remove Special Characters'), ('regex_replace', 'Regex Find & Replace'), ('add_derived_column', 'Add Derived Column'), ('extract_year', 'Extract Year'), ('extract_month', 'Extract Month'), ('extract_day', 'Extract Day'), ('extract_weekday', 'Extract Weekday'), ('extract_quarter', 'Extract Quarter'), ('calculate_age', 'Calculate Age'), ('days_between_dates', 'Days Between Dates'), ('add_days', 'Add Days'), ('subtract_days', 'Subtract Days'), ('normalize_minmax', 'Normalize (Min-Max)'), ('standardize_zscore', 'Standardize (Z-Score)'), ('log_transform', 'Log Transform'), ('sqrt_transform', 'Square Root Transform'), ('absolute_value', 'Absolute Value'), ('round_values', 'Round Values'), ('floor_values', 'Floor Values'), ('ceiling_values', 'Ceiling Values'), ('clip_values', 'Clip Values'), ('scale_by_constant', 'Scale by Constant'), ('label_encode', 'Label Encoding'), ('one_hot_encode', 'One-Hot Encoding'), ('ordinal_encode', 'Ordinal Encoding'), ('binary_encode', 'Binary Encoding'), ('frequency_encode', 'Frequency Encoding'), ('conditional_column', 'Conditional Column (IF ELSE)'), ('bin_values', 'Bin Numerical Values'), ('percentage_column', 'Percentage Column'), ('average_columns', 'Average Columns'), ('count_non_null', 'Count Non-Null Values'), ('compute_mean', 'Mean'), ('compute_median', 'Median'), ('compute_mode', 'Mode'), ('compute_std', 'Standard Deviation'), ('compute_variance', 'Variance'), ('compute_skewness', 'Skewness'), ('compute_kurtosis', 'Kurtosis'), ('correlation_matrix', 'Correlation Matrix'), ('validate_emails', 'Validate Emails'), ('validate_phones', 'Validate Phones'), ('validate_dates', 'Validate Dates'), ('detect_outliers_iqr', 'Detect Outliers (IQR)'), ('detect_outliers_zscore', 'Detect Outliers (Z-Score)'), ('merge_datasets', 'Merge Datasets')], max_length=50),
        ),
    ]
